### ISSUE TITLE
Stats / Insights

### ISSUE THREAD

**Issue by ebertmi** [ebertmi/webbox#16]
We need to figure out which stats and insights we need to display and which events and user interaction we need to capture in order to display those.

The Stats / Insights page should have at least **two** main areas.
## Stats
- [x] Number of user saved documents for the embed
- [x] Number of common errors for this example
- [x] Maybe results of unit tests for users
- [x] Number of runs and errors
## Interaction
- [x] Sent In Embeds
- [x] Enable/Disable _Send To Teacher_
- [x] Enable/Disable _Share with all_
## User Activity Graph
- [x] Maybe plot a activity graph for the embed only
