### ISSUE TITLE
Application Meta

### ISSUE THREAD

**Issue by ebertmi** [ebertmi/webbox#2]
# Design-Entscheidungen:

Entscheidungen müssen noch getroffen werden.
## UI
- [x] CSS-Framework
- [x] SASS?
- [x] webpack?
- [x] Schrift: http://typecast.com/preview/google/Lato/Arimo
  https://www.google.com/fonts/specimen/Merriweather
## Server
- [x] Templating Engine: Jade und react
- [x] Datenbank? => rethinkDB mit thinky ODM/ORM https://thinky.io/documentation/introduction/

Links:
http://mph-web.de/realtime-timeline-with-hapi-js-nes-and-rethinkdb/
https://thinky.io/documentation/introduction/
http://mph-web.de/build-a-restful-api-using-hapi-js-and-mongodb/
https://medium.com/@poeticninja/authentication-and-authorization-with-hapi-5529b5ecc8ec#.78wqv35db
http://hapijs.com/tutorials/validation
http://sass-lang.com/
https://github.com/SimonDegraeve/hapi-webpack-plugin
