### ISSUE TITLE
[IDE] Skulpt/Bayreuth 

### ISSUE THREAD

**Issue by ebertmi** [ebertmi/webbox#47]
Last things todo before testing:
- [x] Fix statusbar displayname for skulpt based projects
  - Remove hardcoded Displayname in languages.js and use the embed.meta.embedTyp
- [x] Allow to access skulpt embeds without being logged in
- [x] Change IDE project logic to support logging for anonyoumus students
- [x] Embed controller should sent websocket auth for anonyoumus users
- [x] Hide "New Terminal"
- [x] Same-Origin Header for embedding on foreign pages
